#!/bin/bash

# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Get the hostname of the server
HOST_NAME=$(hostname)

# Configure Nginx to add custom response header
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Restart Nginx to apply changes
service nginx restart
