#!/usr/bin/env bash
# ping an IP address passed as an argument
# accepts a string as an argument
# displays "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument
# ping the IP 5 times

if [ ! -z "$1" ]
then
	ping "$1" -c5 
else
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
fi
