#!/usr/bin/env bash
#Bash script that displays a list of currently running processes.
echo "USER   PID %CPU %MEM     VSZ    RSS   TTY STAT START TIME COMMAND"
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
